version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=new_password
    ports:
      - "5432:5432"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 

  web:
    build: .
    command: python app.py 
    volumes: 
      - .:/code/
    depends_on:
      - db
    ports:
      - "5000:5000"

    
 
  